### ISSUE TITLE
Stop splitting single select options to columns in Data analysis export

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2400]
# Context
Currently users can export options question answers 2 ways from Flow:

- via Data Cleaning Export: all selected options are combined in one cell and pipe separated for multiple select option questions
- via Data Analysis Export: one column with all the selected options, followed by column per option

## Example of single select option question
https://user-images.githubusercontent.com/12456965/32102822-43813052-bb1e-11e7-8dfc-3eaacaf30d66.jpg

## Example of multi select option question

https://user-images.githubusercontent.com/12456965/32102826-456a588a-bb1e-11e7-9d70-36fb70b78b23.jpg

In the research done here: akvo/akvo-product-design#273 we learned that having separate columns for option questions (multiple select) is a helpful way to structure data. This avoids Salim or Petra having to have to clean up the data on their own. We also, however, learned that having these options split for all option questions, regardless of single or multiple select, makes no sense for single select option questions.

# Ideas
## For Data Cleaning Exports
- create separate columns for each option but **only** for option that have multiple select enabled (follow the same pattern as in Data analysis export - so one column with all answers selected and then separate columns per option) 
- do not separate columns for option questions that are only single select
## For Data Analysis Exports
- keep as it is for option question with multiple select enabled
   - summary column with the question name (or variable name) and all selected answers in the cell divided by pipe
   - each column per option and indicated with 1/0 is option selected
- do not create separate columns for options where multiple select is not enabled, so for single select options

# Questions 
How will this affect data cleaning?

**Comment by janagombitova** [comment]
Based on the discussion we had around ensuring column names are not duplicated (here: https://github.com/akvo/akvo-flow/issues/2315) I suggest to keep the **Data cleaning export** structure as it is. For the **Data analysis export** we already split the option questions into multiple columns. 

However, the issue is that for single select option questions the splitting of options to separate columns in not helpful and not needed. The change should then ensure that for Data analysis exports we only create the separate option columns for option questions where more than one answer is allowed (multi select option questions)

**Comment by stellanl** [comment]
Currently the comprehensive report also splits options into separate columns.
(It also - like the data cleaning report - does not put variable names in the column headers.)
This could be a bug that should be fixed.

**Comment by janagombitova** [comment]
@stellanl should we create an issue to how to handle the data in Comprehensive reports? I think it should have one structure or the other (Data cleaning export structure or Data analysis export structure). What are your thoughts?

**Comment by stellanl** [comment]
Yes, it would be good with a documented discussion and decision; right now we are just coasting :)

**Comment by janagombitova** [comment]
@stellanl I am still waiting for one reply from a user on how they use the Comprehensive report. I will put them all in the issue here https://github.com/akvo/akvo-flow/issues/2469 and then we can take it further.

**Comment by janagombitova** [comment]
@stellanl I just got data out of UAT1 in a Data analysis export and my single select option question is still showing those extra columns. Any ideas why? 

<img width="198" alt="screen shot 2018-02-13 at 15 43 56" src="https://user-images.githubusercontent.com/12456965/36155468-c0a12482-10d4-11e8-9044-2df53678a75b.png">

**Comment by janagombitova** [comment]
after speaking to @stellanl he explained that the fix is not merged yet, so I was too excited to test. Will cross check again once merged. Please ignore my comment above.

**Comment by janagombitova** [comment]
Ohh this is brilliant! and works well also if a user changes single select to multi select and then back. again.
